### ISSUE TITLE
log not read and logtailer stoped

### ISSUE THREAD

**Issue by ct1jib** [dg9vh/MMDVMHost-Websocketboard#37]
**Describe the bug**
I don't know when this started but today i give a free time to my old hotspot, with dmrhost + logtailer, until March 23 works great but now shows the error attached 

**To Reproduce**

python3 ./logtailer.py

**Expected behavior**

**Screenshots**

2024-09-13 18:59:05,740 INFO Loading DMR_IDs from file
Traceback (most recent call last):
  File "/opt/MMDVMDash/./logtailer.py", line 427, in <module>
    main()
  File "/opt/MMDVMDash/./logtailer.py", line 417, in main
    load_callsign_database()
  File "/opt/MMDVMDash/./logtailer.py", line 406, in load_callsign_database
    dmrids[tokens[0]] = tokens[1] + "$" + tokens[2].replace("\r", "").replace("\n", "") + "$"
IndexError: list index out of range

- OS: bullseye 11.11

**Additional context**

seems to me that something is wrong on read DMRids.dat

**Comment by ct1jib** [comment]
solved
